# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: liveneeq-blog
email: it@liveneeq.com
description: > # A blog of liveneeq.com.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://onecampus.github.io/" # the base hostname & protocol for your site
twitter_username: liveneeq
github_username: onecampus

disqus_shortname: liveneeqblog

# authors:
#   - flowerwrong
#
# flowerwrong:
#   github: 'https://github.com/FlowerWrong'
#   twitter: 'https://twitter.com/Dennis69249870'
#   avatar: 'https://avatars2.githubusercontent.com/u/5362640?v=3&s=460'
#   facebook: ''

# @see http://jekyllrb.com/docs/configuration/
highlighter: true
markdown: redcarpet
redcarpet:
  extensions:
    - hard_wrap
    - no_intra_emphasis
    - autolink
    - strikethrough
    - fenced_code_blocks


timezone: 'Asia/Shanghai'
